image: python:3.9

stages:
  - test

tests:
  stage: test
  script:
    - pip install -r requirements.txt

    - python3 manage.py test mysite.polls.tests.IndexViewTest

    - python3 manage.py test mysite.polls.tests.ScrapViewTest

    - python3 manage.py test mysite.polls.tests.ResultViewTest

    - python3 manage.py test mysite.polls.tests.SignUpViewTest

    - python3 manage.py test mysite.polls.tests.DeleteAccountViewTest

    - python3 manage.py test mysite.polls.tests.ListViewTest

    - python3 manage.py test mysite.polls.tests.AddItemViewTest

    - python3 manage.py test mysite.polls.tests.DeleteItemViewTest
  only:
    - main
