image: python:3.9

stages:
  - test

tests:
  stage: test
  script:
    - pip install -r requirements.txt

    - python3 manage.py test mysite.polls.tests.IndexViewTest

    - python3 manage.py test mysite.polls.tests.ScrapViewTest

    - python3 manage.py test mysite.polls.tests.SignUpViewTest

  only:
    - main
