# Generated by Django 5.0.3 on 2024-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_liste_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_course', models.CharField(max_length=50)),
                ('date_course', models.DateTimeField(verbose_name='date de la course')),
                ('lieu_course', models.CharField(max_length=50)),
                ('longueur', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Liste',
        ),
    ]
