# Generated by Django 5.0.3 on 2024-03-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_course_delete_liste'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courset',
        ),
    ]
