# Generated by Django 5.0.3 on 2024-03-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_course_courset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courset',
            new_name='Course',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_inscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'inscription"),
        ),
    ]
