# Generated by Django 5.0.3 on 2024-03-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_courset_course_alter_user_date_inscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pseudo',
            new_name='username',
        ),
    ]
